### ISSUE TITLE
Tabbar的快捷键不能用

### ISSUE THREAD

**Issue by pokoblin** [humiaozuzu/dot-vimrc#16]
我是在OSX下用Terminal里ssh远程连接ubuntu server来使用vim的
配置里所说的alt + Num 来切换标签不起作用
应该怎么解决？

**Comment by tclh123** [comment]
try <Esc> + num

**Comment by pokoblin** [comment]
@tclh123 果然好用，不过有点别扭，我在 .vimrc 里设置一下，多谢。

**Comment by tclh123** [comment]
@bindiry 

```
nmap <c-x> :Tbbd<cr>
nmap H :Tbbp<cr>
nmap L :Tbbn<cr>
```

我现在的配置，感觉还行

**Comment by andygithubchen** [comment]
try + num  这个是什么？？求解 @tclh123
