### ISSUE TITLE
可以在windows gvim上安装吗？

### ISSUE THREAD

**Issue by yaotian** [humiaozuzu/dot-vimrc#3]
好像不可以。
可以的话，具体什么步骤？

一直在linux上和macbook上用， 但最近需要在window上使用，但发现部署不易。

**Comment by yoxyue** [comment]
我在win7下安装过,可以参考我的 http://yoxyue.com/2012/10/17/gVIM-on-win7/

**Comment by humiaozuzu** [comment]
多谢。我把链接添加到 readme 中去

**Comment by yoxyue** [comment]
my post change to : https://gist.github.com/yoxyue/6102027
